### ISSUE TITLE
Page jeu // intégration

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#28]
2 petites modifs sur le template jeu uniquement please (pas sur les autres template du site pour le moment exemple : https://chaleur-rugby.fk-agency.net/jeux/quizz/ ) :

1. =>  laisser le header en `position:relative;` pour qu'il ne scroll pas au-dessus du jeu
2. => Ajouter un bouton "scroll to top" après un scroll de 100px Cf https://codepen.io/matthewcain/pen/ZepbeR tu peux reprendre ce magnifique bouton de ma création si tu le souhaite :
[Groupe 18074.svg.gz](https://github.com/FK-Agency/ME-chaleur-rugby/files/7635697/Groupe.18074.svg.gz)

**Comment by CharlieSaso** [comment]
OK

**Comment by Sinoe** [comment]
ok merci, par contre peux-tu stp :
1.  enlever le padding sur `.c-main`
2. mettre ScrollTop en bottom 40px  (là il est un peu sous la box tarte au citron)
```css
#scrollTop {

    bottom: 40px;
    ...
    }
```

**Comment by Sinoe** [comment]
Ok j'ai ajouté sur le main.css en bas du fichier build en attendant que tu puisses l'ajouter aux sources pour présentation client
```css
.single-jeux main.c-main {
    padding-top: 0;
}
#scrollTop{
  transform: scale(1.25);
    bottom: 45px;
    background: white;
}
```
