### ISSUE TITLE
Général // Affichage mobile / ajouter de la marge sur les côtés

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#36]
Demande du client d'ajouter de la marge sur les côtés en mobile.

Je pense que passer o-wrapper en `padding: 0 20px;` VS `padding: 0 10px;` fait le taff
```css
.o-wrapper {
    width: 100%;
    padding: 0 20px;
}
```
