### ISSUE TITLE
Pages LP Jeux // * / Agrandir les images des lots 2 et 3

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#37]
Agrandir les images des lots 2 et 3 sur les pages LP lots
A priori : 
```css
@media (min-width: 64em)
.c-gifts__item:nth-child(n + 3) .c-gifts__push img {
    max-width: 480px;
}
```
fait le taff mais comportement à vérifier pour les résolutions plus basses aussi
![Concours-photo-Hyper-Heating-Ultimate-–-Chaleur-Rugby](https://user-images.githubusercontent.com/17780287/144474648-0697ccf7-b388-472d-bb5b-31397d4607f1.png)
