### ISSUE TITLE
Page home + page LP jeux // enlever le font-weight bold sur les box CTA

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#38]
Mettre en font-weight normal les contenus "box" de la home et des pages jeux pour que le client puisse ajouter lui-même des <b> si besoin dedans :
![Chaleur-Rugby (13)](https://user-images.githubusercontent.com/17780287/144475509-209cb6e3-11ca-4d13-a7fa-4c77eb2b8020.png)
![Concours-photo-Hyper-Heating-Ultimate-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/144475520-27d72a1a-bb53-4b25-b47d-ee64d0716290.png)

```css
.c-cover__box p,
.c-quiz__desc {
    font-weight: normal;
}
```
