### ISSUE TITLE
Inté slider Instagram Vidéo à répercuter sur tes fichiers

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#40]
2 changements sur le slider poussées en pp => à reprendre correctement :
Page template home (MAJ du lien vers le bon compte insta )
```php
<div class="c-instagram">
	<div class="o-wrapper">
		<div class="c-instagram__content">
			<h2 class="c-instagram__title">Instagram <small><a href="https://www.instagram.com/mitsubishielectric_fr/" target="_blank">@mitsubishielectric_fr</a></small></h2>
				<div class="c-instagram__slider">
					<div class="c-instagram__slides js-slider-insta">
						<?php echo do_shortcode('[instagram-feed]'); ?>
					</div>
				</div>
		</div>
	</div>
</div>
```

Et inté des vidéos ajouté à l'arrache sur main.css :
```css
/*BAD*/
.c-instagram__slides,
.c-instagram__slides .slick-list,
.c-instagram__slides .slick-track, 
.c-instagram__slide{
  height:100%;
  min-height:100%;
}
.c-instagram__slide a{
height: 248px; /* précédemment height:100%; mais si on ne met pas la valeur fixe, ça ajouter 1/2px de noir au dessus des images*/
display:flex;
align-items:center;
border-radius:10px;
background:black;
overflow:hidden;
}
.c-instagram__slide img{
border-radius:0;
}
```
