### ISSUE TITLE
Pages prono // recette front - Mobile

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#62]
-[ ] Header "Profil" : laisser l'affichage en mode row en mobile 
Possible fix (Ajout  `flex-direction: row;     flex-wrap:wrap;`) :
```css
.c-pronostics--stats--list {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
```

-[ ] Box match : laisser l'affichage en mode row en mobile  + limiter la hauteur de la box + centrer le contenu
Possible fix 
```css
.c-pronostics__match__bet {
    display: flex;
    padding: 20px;
    justify-content: space-between;
    align-items: flex-end;
    flex-direction: row;
    align-items: center;
    flex-wrap: wrap;
}
.c-pronostics__match__bet--player {
    width: calc(50% - 20px);
}
.c-pronostics__match__bet--bet{
width:40px;
}
.c-pronostics__match__bet--betmobile{
width:100%;
}
.c-pronostics__match__bet--betmobile--nav{
    display: flex;
    margin: 0 auto;
    margin-top: 20px;
    flex-direction: column;
    align-items: center;
    width: 100%;
}
p.info-loose {
         margin-bottom: 10px;
}
```

- [x] limiter la hauteur des box matchs : changer le padding sur le header + limiter la marge entre les éléments 
Possible fix 

```css 
.c-pronostics__match__intro {
    display: flex;
    flex-direction: column;
    background-color: #1f419b;
    background-color: var(--color-primary);
    color: #ffffff;
    padding: 20px;
    justify-content: space-between;
}
.c-pronostics__match__intro * {
    margin-bottom: 5px;
}
```

Normalement ça devrait donner ça :
![Page-de-pronostics-–-Chaleur-Rugby (5)](https://user-images.githubusercontent.com/17780287/149343964-c7b88765-da5e-4f77-b42a-8731e989a272.png)
![Page-de-pronostics-–-Chaleur-Rugby (4)](https://user-images.githubusercontent.com/17780287/149343987-a7dcef91-dd77-451f-8d0a-ca1f2f424170.png)
