### ISSUE TITLE
Page classement prono // intégration Desktop + Mobile

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#65]
Hello,

Retours sur l'inté Desktop :
Il faudrait ajouter un peu de padding sur les colonnes du tableau pour que les valeurs ne se chevauchent pas stp et peut-être revoir la largeur, elles ont pas besoin de faire toutes 25%, on peut limiter la première et la dernière par exemple :
![Page-de-Classement-–-Chaleur-Rugby (3)](https://user-images.githubusercontent.com/17780287/150962195-c63169a2-640b-46c7-a0eb-de800db2aef7.png)

Et si tu peux ajouter ça comme style en mobile pour fix l'affichage des pages classement Mobile stp :
```css
.c-classement__head,
.c-classement__line{
    display:flex;
    flex-wrap: wrap;
    padding:20px;
}
.c-classement__head p,
.c-classement__head p:last-child,
.c-classement__line div{
    width:100%;
    text-align:center;
}
.c-classement__line div{
      font-size:1rem;
}
.c-classement__line--num{
      display:inline-block;
      margin-bottom:0.5rem;
}
```

![Page-de-Classement-–-Chaleur-Rugby (2)](https://user-images.githubusercontent.com/17780287/150941316-06c86c1f-53d5-4c7b-93a3-c2ae8da9a4ef.png)

![Page-de-Classement-–-Chaleur-Rugby (1)](https://user-images.githubusercontent.com/17780287/150941309-31eae247-cbdf-4c34-beda-16f287af9843.png)
