### ISSUE TITLE
Inté page "Statistiques" 

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#72]
- [x] Général:
Peux-tu stp mettre un niveau de largeur supérieur sur `o-wrapper` (la largeur au-dessus si ça existe déjà), sinon `width:96%` / `max-width:1400px` ?

- [x] Header :
1. Titres niveaux 6 + changer les libélés
Filtre 1 : `<h6>Type de donnée:</h6>`
Filtre 2 : `<h6>Jeux passés / en cours</h6>`

2. Style des boutons + ul
```css
.filter_nav{
margin-left:0;
}
.filter_nav .c-btn {
    height: 40px;
    align-items: center;
    color: #ed1e25;
    color: var(--color-secondary);
    display: inline-flex;
    background-color: #fff;
    padding: 0 20px;
    font-size: 1rem;
    font-weight: bold;
    border-radius: 25px;
    white-space: nowrap;
    text-decoration: none;
    transition: all 0.3s ease;
    border: 1px solid currentColor;
}
```
3. Ajouter un `<br><hr></hr><br>` au dessus de `<h6>Liste des jeux</h6>` + remplacer le h4 par un h6

- [x] Tableaux :
1. Revoir la largeur max des colonnes + design des boutons + pagination
```css
table.dataTable {
    table-layout: fixed;
}
table.dataTable.nowrap th, 
table.dataTable.nowrap td {
    white-space: break-spaces;
}
table.dataTable thead th, table.dataTable thead td{
max-width:200px;
}
button.buttons-html5 {
    color: #fff;
    display: inline-flex;
    height: 38px;
    cursor: pointer;
    font-size: 1.125rem;
    align-items: center;
    position: relative;
    font-weight: bold;
    border-radius: 19px;
    white-space: nowrap;
    padding: 0 20px;
    background-color: #ed1e25;
    background-color: var(--color-secondary);
    margin-right: 10px;
}

.dataTables_wrapper .dataTables_paginate,
.dataTables_wrapper .dataTables_paginate > span{
        display: flex;
    justify-content: flex-end;
    align-items: center;
    flex-direction: row;

}
.dataTables_wrapper .dataTables_paginate .paginate_button {
  position: relative;
  display: block;
  padding: 0.5rem 0.75rem;
  margin-left: -1px;
  line-height: 1.25;
  color: #8898aa;
  background-color: #fff;
  border: 1px solid #dee2e6;
}
.page-template-page-table .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
  z-index: 2;
  color: #8898aa;
  text-decoration: none;
  background: #dee2e6 !important;
  border-color: rgb(31, 65, 155);
}
.dataTables_wrapper .dataTables_paginate .paginate_button:focus {
  z-index: 2;
  outline: 0;
  box-shadow: none;
}
.dataTables_wrapper .dataTables_paginate .paginate_button:not(:disabled):not(.disabled) {
  cursor: pointer;
}
.dataTables_wrapper .dataTables_paginate .paginate_button,
.page-template-page-table .page-item span {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  margin: 0 3px;
  border-radius: 50% !important;
  width: 36px;
  height: 36px;
  font-size: 0.875rem;
}
.page-template-page-table .dataTables_wrapper .dataTables_paginate .paginate_button.current {
  background: rgb(31, 65, 155) !important;
  border-color: rgb(31, 65, 155);
  color:white !important;
}
.dataTables_wrapper .dataTables_paginate .paginate_button:hover {
    color: white !important;
    border: 1px solid #111;
    background: #585858;
    
}
```
2. Revoir le comportement datatable (à test avec les vrais données...) // fix 2 colonnes gauches en cas de scroll + texte en FR + select multi + nombre de lignes à afficher au choix + position bouton DL
Charger fix column https://cdn.datatables.net/fixedcolumns/4.0.1/js/dataTables.fixedColumns.min.js
```js
var buttons = ["excel", "print"];
var options = {
    keys: !0,
    select: {
        style: "multi"
    },
    dom: 'lftripB',
    buttons: buttons,
    "order": [],
    "lengthMenu": [
        [25, 50, 100, -1],
        [25, 50, 100, "Tous"]
    ],
    language: {
        // "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/French.json",
        "lengthMenu": "Voir _MENU_ enregistrements par page",
        "zeroRecords": "Pas d'enregistrement",
        "info": "Page _PAGE_ de _PAGES_ (total)",
        "infoEmpty": "Pas d'enregistrement",
        "infoFiltered": "(filtré à partir de _MAX_ enregistrements)",
        "sSearch": "Rechercher :",
        paginate: {
            previous: "<",
            next: ">"
        }
    },
    fixedColumns: {
        left: 2
    }
};
$('.societe_distributeur_table').DataTable(options);
```
