### ISSUE TITLE
Pages stats bug fond th/td au scroll horizontal

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#89]
Peux-tu ajouter le css suivant stp sur `css/components/_statistiques.css`

```css
.page-template-page-table  tr.odd>th,
.page-template-page-table  tr.odd>td{
    background-color:#f9f9f9;
}
.page-template-page-table  tr.even>th,
.page-template-page-table  tr.even>td{
    background-color:#fff;
}
.page-template-page-table  tr.odd>th.green,
.page-template-page-table  tr.odd>td.green,
.page-template-page-table  tr.even>th.green,
.page-template-page-table  tr.even>td.green{
    background-color: rgba(152, 237, 128, 0.5);
}
.page-template-page-table  tr.odd>th.red,
.page-template-page-table  tr.odd>td.red,
.page-template-page-table  tr.even>th.red,
.page-template-page-table  tr.even>td.red{
    background-color: rgba(237, 30, 37, 0.5);
}
.page-template-page-table  tr.odd>th.yellow,
.page-template-page-table  tr.odd>td.yellow,
.page-template-page-table  tr.even>th.yellow,
.page-template-page-table  tr.even>td.yellow{
    background-color: rgba(232, 213, 72, 0.5);
}

.page-template-page-table  tr>th.dtfc-fixed-left,
.page-template-page-table  tr>td.dtfc-fixed-left{
    z-index:2;
}
```

Pour fix la superposition au scroll des éléments fix du tableau :

![Page-Statistiques-–-Chaleur-Rugby (7)](https://user-images.githubusercontent.com/17780287/162150490-cecc504f-002a-4d11-9f78-f3f19ae7bf5d.png)

**Comment by Sinoe** [comment]
Yo !
On a 2 fois `.page-template-page-table` :

```scss
.page-template-page-table {
          .page-template-page-table  tr.odd>th{
...
```
Du coup si tu peux remplacer ce que t'as mis par 

```css
tr.odd>th,
tr.odd>td{
    background-color:#f9f9f9;
}
tr.even>th,
tr.even>td{
    background-color:#fff;
}
tr.odd>th.green,
tr.odd>td.green,
tr.even>th.green,
tr.even>td.green{
    background-color: rgba(152, 237, 128, 0.5);
}
tr.odd>th.red,
tr.odd>td.red,
tr.even>th.red,
tr.even>td.red{
    background-color: rgba(237, 30, 37, 0.5);
}
tr.odd>th.yellow,
tr.odd>td.yellow,
tr.even>th.yellow,
tr.even>td.yellow{
    background-color: rgba(232, 213, 72, 0.5);
}

tr>th.dtfc-fixed-left,
tr>td.dtfc-fixed-left{
    z-index:2;
}
```
please
