### ISSUE TITLE
Corrections page stats 

### ISSUE THREAD

**Issue by Sinoe** [FK-Agency/ME-chaleur-rugby#96]
- [x] enlever les 01 sur les concours
![Page-Statistiques-–-Chaleur-Rugby (8)](https://user-images.githubusercontent.com/17780287/164011883-b01e4c2f-b331-4012-b8bd-7c817fd3f171.png)

- [x] passer le jeu prono en mode jeu passé
![Page-Statistiques-–-Chaleur-Rugby (9)](https://user-images.githubusercontent.com/17780287/164012004-98cb2cd4-7f11-413d-a125-4d70592e4ffa.png)

- [x] Par défaut, si rien n'est sélectionné, arriver sur la page stat sur la partie Distributeurs > Agences > En cours
![Page-Statistiques-–-Chaleur-Rugby (10)](https://user-images.githubusercontent.com/17780287/164012278-b712c910-a736-44e3-b9d9-c5362b2ecb79.png)

- [x] ordre d'affichage des colonne sur la page stats Distrib : Concours photo / concours vidéos / golden ticket
(si possible)

- [x] couleur des TD sur les colonnes après tri qui saute (ajout class `sorting_n` par datatable à overider),
```scss
tr.odd>th.green,
tr.odd>td.green,
tr.even>th.green,
tr.even>td.green{
    background-color: rgba(152, 237, 128, 0.5);
    &.sorting_1,
    &.sorting_2,
    &.sorting_3{
        background-color: rgba(152, 237, 128, 0.5);
    }
}
tr.odd>th.red,
tr.odd>td.red,
tr.even>th.red,
tr.even>td.red{
    background-color: rgba(237, 30, 37, 0.5);
    &.sorting_1,
    &.sorting_2,
    &.sorting_3{
        background-color: rgba(237, 30, 37, 0.5);
    }
}
tr.odd>th.yellow,
tr.odd>td.yellow,
tr.even>th.yellow,
tr.even>td.yellow{
    background-color: rgba(232, 213, 72, 0.5);
    &.sorting_1,
    &.sorting_2,
    &.sorting_3{
        background-color: rgba(232, 213, 72, 0.5);
    }
}
```
